-- `judgment.location`: where the call came from (sd:2950).
--
-- `caller` and `stage` say which program asked and for which decision; they
-- do not say from where. `location` is the caller's directory: the git
-- toplevel of its working directory, else that directory. It is a key column
-- as `skill_use.cwd` is: `sd_db.judgment.record` stores a path under `$HOME`
-- as `~/` plus the relative path. A value over 255 characters or with a
-- control character is stored as NULL, so a bad location costs the row its
-- location and never the row.
--
-- The column only, and every existing row reads NULL: no row recorded one.
--
-- `ADD COLUMN` for 016's reason: SQLite adds a nullable column in place,
-- touches no other table and moves no row.
-- The reverse, run by hand with the runner, the dashboard and the serve agent
-- stopped:
--
--   BEGIN;
--   ALTER TABLE judgment DROP COLUMN location;
--   PRAGMA user_version = 20;
--   COMMIT;

ALTER TABLE judgment ADD COLUMN location TEXT;
