"""Remaining runner acceptance uses real clones, processes, and durable evidence."""

import contextlib
import io
import json
import os
import subprocess
import sys
import time
import unittest
from datetime import UTC, datetime, timedelta
from pathlib import Path
from unittest.mock import patch

from sd_db import runner as store
from sd_db import runner_exec, runner_journal, workflow
from sd_runner import cli, controls, maintenance, reconciliation, restoration

from . import test_runtime as fixtures


class Closeout(unittest.TestCase):
    def setUp(self):
        self.fixture = fixtures.Fixture()
        self.fixture.setUp()
        self.addCleanup(self.fixture.doCleanups)
        self.root, self.db, self.config = self.fixture.root, self.fixture.db, self.fixture.config

    def palette(self, source):
        program = self.root / "finite-command"
        program.write_text("#!" + sys.executable + "\n" + source)
        program.chmod(0o755)
        catalog = self.root / "commands.yaml"
        entry = {"argv": [str(program)], "screens": ["item"], "scope": "worktree", "mutates": True}
        catalog.write_text("version: 1\ncommands:\n  fixture: " + json.dumps(entry) + "\n")
        prepared = runner_exec.prepare(self.db, self.fixture.item, "fixture", {},
            expected_revision=workflow.item_state(self.db, self.fixture.item)["revision"],
            expected_catalog=runner_exec.catalog(path=catalog)["sha256"], path=catalog, who="operator")
        request = store.claim(self.db, prepared["assignments"][0]["id"], owner=self.fixture.runner.owner,
                              work_root=self.config.work, retention_root=self.config.retention)
        return request, prepared["execution"], program

    def test_native_finite_exec_completes_original_note_and_preserves_item_status(self):
        request, descriptor, _ = self.palette("import os\nprint('owned=' + os.environ['SD_ASSIGNMENT'])\nprint('secret=' + str(os.getenv('FIXTURE_SECRET')))\n")
        before = workflow.item_state(self.db, self.fixture.item)["item"]["status"]
        with patch.dict(os.environ, {"FIXTURE_SECRET": "private"}), patch("sd_runner.runtime.provider_command", side_effect=AssertionError("provider dispatch")), patch.object(self.fixture.runner, "ship", side_effect=AssertionError("ship dispatch")):
            result = self.fixture.runner.execute(self.db, request)
        self.assertEqual(result["end_step"], "released", result)
        note = runner_exec.read_execution(self.db, descriptor["note"])
        self.assertEqual(note["exit_code"], 0)
        self.assertIn("owned=" + result["id"], note["output"])
        self.assertIn("secret=None", note["output"])
        self.assertEqual(workflow.item_state(self.db, self.fixture.item)["item"]["status"], before)
        self.assertEqual(self.db.execute("SELECT count(*) FROM note WHERE item=? AND kind='exec'", (self.fixture.item,)).fetchone()[0], 1)

    def test_dirty_exec_keeps_clone_and_lease_without_commits_or_ship(self):
        request, descriptor, _ = self.palette("from pathlib import Path\nPath('precious').write_text('generated bytes')\nprint('done')\n")
        result = self.fixture.runner.execute(self.db, request)
        self.assertEqual(result["end_step"], "kept", result)
        self.assertIsNone(result["released_at"])
        self.assertEqual((Path(result["work_path"]) / "precious").read_text(), "generated bytes")
        self.assertTrue((Path(result["retained_path"]).parent / "kept.tar").is_file())
        self.assertEqual(runner_exec.read_execution(self.db, descriptor["note"])["exit_code"], 0)
        self.assertEqual(workflow.item_state(self.db, self.fixture.item)["item"]["status"], "ready")
        clone = Path(result["work_path"])
        fixtures.git(clone, "add", "precious")
        fixtures.git(clone, "commit", "-qm", "operator resolved command output")
        selected = store.queue_state(self.db, request["id"])
        with patch("sd_runner.controls.Runner", return_value=self.fixture.runner):
            resumed = controls.resume(self.config, request["id"], expected_revision=selected["revision"], expected_run=result["id"], who="operator")
        self.assertEqual(resumed["status"], "done")
        self.assertIsNotNone(resumed["run"]["released_at"])
        with self.assertRaisesRegex(store.RunnerRefused, "single-use"):
            store.requeue(self.db, request["id"], expected_revision=resumed["revision"], who="operator")

    def test_catalog_drift_refuses_before_supervisor_or_command(self):
        request, descriptor, program = self.palette("print('must not run')\n")
        program.write_text(program.read_text() + "# changed\n")
        result = self.fixture.runner.execute(self.db, request)
        self.assertIsNone(result["supervisor_pid"])
        self.assertIn("changed", result["detail"])
        self.assertFalse(Path(descriptor["output_path"]).exists())
        self.assertEqual(workflow.item_state(self.db, self.fixture.item)["item"]["status"], "ready")

    def test_lost_supervisor_response_uses_receipt_without_replaying_command(self):
        request, descriptor, _ = self.palette("print('one dispatch')\n")
        original = self.fixture.runner.action
        def lost(connection, child, selected, action, deadline, **extra):
            result = original(connection, child, selected, action, deadline, **extra)
            if action == "exec":
                raise store.RunnerRefused("response lost after completed command")
            return result
        with patch.object(self.fixture.runner, "action", side_effect=lost):
            result = self.fixture.runner.execute(self.db, request)
        self.assertEqual(result["outcome"], "done", result)
        self.assertIsNotNone(result["released_at"])
        note = runner_exec.read_execution(self.db, descriptor["note"])
        self.assertEqual(note["exit_code"], 0)
        self.assertEqual(note["output"], "one dispatch\n")

    def test_crash_after_exec_receipt_recovers_completed_note_without_dispatch(self):
        request, descriptor, _ = self.palette("print('one process before crash')\n")
        request_file = self.root / "request.json"
        request_file.write_text(json.dumps(request))
        worker = self.root / "crash_exec.py"
        worker.write_text("""import json,os,sys
from pathlib import Path
from sd_db.database import connect
from sd_runner.runtime import Config,Runner
root=Path(sys.argv[1]); config=Config(root/'db/sd.db',root/'work',root/'retained',root,root,interval=.1)
runner=Runner(config,freezer=lambda path:None); original=runner.action
def crash(connection,child,request,action,deadline,**extra):
    result=original(connection,child,request,action,deadline,**extra)
    if action=='exec': os._exit(73)
    return result
runner.action=crash
runner.execute(connect(config.database),json.loads((root/'request.json').read_text()))
""")
        environment = {**os.environ, "PYTHONPATH": os.pathsep.join([str(fixtures.ROOT), str(fixtures.ROOT.parent / "local-sd-db")])}
        result = subprocess.run([sys.executable, str(worker), str(self.root)], env=environment, capture_output=True, text=True, timeout=15, check=False)
        self.assertEqual(result.returncode, 73, result.stderr)
        self.assertIsNone(runner_exec.read_execution(self.db, descriptor["note"])["ended"])
        with patch("sd_runner.runtime.subprocess.Popen", side_effect=AssertionError("replayed process")), patch("sd_runner.runtime.processes.terminate_owned", return_value=False):
            # Only the receipt reader is prohibited from spawning; native cleanup
            # below still performs its real process inventory.
            recovered = self.fixture.runner.execution_result(self.db, store.run_state(self.db, request["run"]["id"]))
        self.assertEqual(recovered["exit_code"], 0)
        self.assertEqual(self.fixture.runner.recover(self.db), [])
        self.assertEqual(store.queue_state(self.db, request["id"])["status"], "done")
        self.assertEqual(runner_exec.read_execution(self.db, descriptor["note"])["output"], "one process before crash\n")

    def test_prune_cli_binds_database_age_outputs_and_never_changes_clone(self):
        request = self.fixture.claim()
        run = self.fixture.run_fixture(request)
        clone = Path(run["retained_path"])
        old = (datetime.now(UTC) - timedelta(days=31)).isoformat()
        self.db.execute("UPDATE runner_run SET released_at=? WHERE id=?", (old, run["id"]))
        (clone.parent / "retention.json").write_text(json.dumps({"retained_at": old}))
        before = restoration.inventory(clone)
        document = maintenance.plan_prune(self.config, self.db)
        self.assertEqual(len(document["entries"]), 1)
        self.assertEqual(document["entries"][0]["run"], run["id"])
        self.assertIn("ignored.txt", document["entries"][0]["preserved"])
        config = self.root / "runner.json"
        config.write_text(json.dumps({"database": str(self.config.database), "retention": str(self.config.retention)}))
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            self.assertEqual(cli.main(["prune", "--config", str(config)]), 0)
        self.assertEqual(json.loads(output.getvalue())["fingerprint"], document["fingerprint"])
        self.assertEqual(restoration.inventory(clone), before)
        with self.assertRaisesRegex(store.RunnerRefused, "30 days"):
            maintenance.plan_prune(self.config, self.db, days=29)
        (clone.parent / "ignored/ignored.txt").write_text("corrupt independent copy")
        with self.assertRaisesRegex(store.RunnerRefused, "independently preserved"):
            maintenance.plan_prune(self.config, self.db)

    def test_discard_plan_binds_revision_and_preserves_dirty_clone(self):
        self.fixture.provider.write_text("from pathlib import Path\nPath('precious').write_text('unfinished')\n")
        request = self.fixture.claim()
        run = self.fixture.run_fixture(request)
        state = store.queue_state(self.db, request["id"])
        before = restoration.inventory(Path(run["work_path"]))
        plan = maintenance.plan_discard(self.config, self.db, request["id"], expected_revision=state["revision"], expected_run=run["id"])
        self.assertTrue(plan["dry_run"])
        self.assertEqual(plan["files"], before)
        self.assertEqual(restoration.inventory(Path(run["work_path"])), before)
        with self.assertRaisesRegex(store.RunnerRefused, "selection changed"):
            maintenance.plan_discard(self.config, self.db, request["id"], expected_revision="stale", expected_run=run["id"])

    def test_recovery_regenerates_missing_journal_with_exact_snapshot(self):
        request = self.fixture.claim()
        plan = reconciliation.plan(self.config)
        entry = plan["entries"][0]
        self.assertEqual(entry["operation"], "journal-from-database")
        result = reconciliation.reconcile(self.config, request["run"]["id"], fingerprint=entry["fingerprint"])
        self.assertTrue(result["ok"])
        self.assertEqual(runner_journal.records(self.config.database), [store.run_state(self.db, request["run"]["id"])])
        self.assertEqual(reconciliation.plan(self.config)["entries"], [])
        self.assertTrue(Path(result["evidence"]).is_file())

    def test_recovery_adopts_newer_or_orphan_journal_without_inventing_delivery(self):
        request = self.fixture.claim()
        newer = self.fixture.runner.persist(self.db, request["run"]["id"], start_step="supervised")
        self.db.execute("UPDATE runner_run SET journal_version=0,start_step='claimed' WHERE id=?", (newer["id"],))
        plan = reconciliation.plan(self.config)["entries"][0]
        reconciliation.reconcile(self.config, newer["id"], fingerprint=plan["fingerprint"])
        recovered = store.run_state(self.db, newer["id"])
        self.assertGreater(recovered["journal_version"], newer["journal_version"])
        self.assertEqual(recovered["outcome"], "blocked")
        self.assertEqual(store.queue_state(self.db, request["id"])["status"], "ending")
        self.db.execute("DELETE FROM runner_lease WHERE run=?", (newer["id"],))
        self.db.execute("DELETE FROM runner_run WHERE id=?", (newer["id"],))
        plan = reconciliation.plan(self.config)["entries"][0]
        reconciliation.reconcile(self.config, newer["id"], fingerprint=plan["fingerprint"])
        self.assertIsNotNone(self.db.execute("SELECT run FROM runner_lease WHERE run=? AND released_at IS NULL", (newer["id"],)).fetchone())
        self.assertEqual(self.fixture.runner.recover(self.db), [])
        self.assertEqual(store.queue_state(self.db, request["id"])["status"], "blocked")

    def test_recovery_stale_conflicting_or_absent_assignment_preserves_evidence(self):
        request = self.fixture.claim()
        original = self.fixture.runner.persist(self.db, request["run"]["id"])
        path = runner_journal.directory(self.config.database) / (original["id"] + ".json")
        before = path.read_bytes()
        self.db.execute("UPDATE runner_run SET detail='conflicting restored copy' WHERE id=?", (original["id"],))
        plan = reconciliation.plan(self.config)["entries"][0]
        with self.assertRaisesRegex(store.RunnerRefused, "same-version"):
            reconciliation.reconcile(self.config, original["id"], fingerprint=plan["fingerprint"])
        self.db.execute("DELETE FROM runner_lease WHERE run=?", (original["id"],))
        self.db.execute("DELETE FROM runner_run WHERE id=?", (original["id"],))
        self.db.execute("DELETE FROM assignment WHERE id=?", (request["id"],))
        plan = reconciliation.plan(self.config)["entries"][0]
        with self.assertRaisesRegex(store.RunnerRefused, "assignment is absent"):
            reconciliation.reconcile(self.config, original["id"], fingerprint=plan["fingerprint"])
        self.assertEqual(path.read_bytes(), before)
        with self.assertRaisesRegex(store.RunnerRefused, "selection changed"):
            reconciliation.reconcile(self.config, original["id"], fingerprint="0" * 64)

    def test_linked_journal_beside_a_real_hold_still_shows_the_hold(self):
        # sd:779: a full restore can link a journal name back; its issue must not hide other runs.
        request = self.fixture.claim()
        held = self.fixture.runner.persist(self.db, request["run"]["id"])
        self.db.execute("DELETE FROM runner_lease WHERE run=?", (held["id"],))
        self.db.execute("DELETE FROM runner_run WHERE id=?", (held["id"],))
        self.db.execute("DELETE FROM assignment WHERE id=?", (request["id"],))
        linked = runner_journal.directory(self.config.database) / ("d" * 32 + ".json")
        linked.write_bytes(b"restored material")
        os.link(linked, self.root / "restore-material")
        plan = reconciliation.plan(self.config)
        self.assertEqual([(entry["run"], entry["blocked"]) for entry in plan["entries"]],
                         [(held["id"], "assignment is absent; restore a database backup containing its original work")])
        self.assertEqual([(issue["entry"], issue["blocked"]) for issue in plan["journal_issues"]],
                         [(linked.name, "unsafe, unowned, linked or oversized journal entry")])
        with self.assertRaisesRegex(store.RunnerRefused, "explicit quarantine"):
            reconciliation.reconcile(self.config, held["id"], fingerprint=plan["entries"][0]["fingerprint"])

    def test_journal_issue_withholds_the_entry_of_the_run_it_names(self):
        request = self.fixture.claim()
        self.fixture.runner.persist(self.db, request["run"]["id"])
        # Behind its journal, the run would otherwise show an entry whichever file is the issue.
        self.db.execute("UPDATE runner_run SET journal_version=journal_version-1 WHERE id=?", (request["run"]["id"],))
        for suffix in (".lock", ".json", ".partial"):
            with self.subTest(suffix=suffix):
                path = runner_journal.directory(self.config.database) / (request["run"]["id"] + suffix)
                material = path.with_suffix(".partial") if suffix == ".partial" else self.root / ("restore-material" + suffix)
                if suffix == ".partial":
                    material.write_bytes(b"interrupted")
                else:
                    os.link(path, material)
                plan = reconciliation.plan(self.config)
                material.unlink()
                self.assertEqual(plan["entries"], [])
                self.assertEqual([issue["entry"] for issue in plan["journal_issues"]], [path.name])

    def test_two_daemons_cannot_reconcile_or_dispatch_same_database(self):
        script = self.root / "daemon_fixture.py"
        marker = self.root / "first-dispatched"
        script.write_text("""import sys,time
from pathlib import Path
from unittest.mock import patch
from sd_runner.runtime import Config,Runner
from sd_db.runner import RunnerRefused
root=Path(sys.argv[1]); marker=root/'first-dispatched'
config=Config(root/'db/sd.db',root/'work',root/'retained',root,root,interval=.1)
def tick(self,connection):
    marker.write_text(self.owner)
    time.sleep(5)
try:
    with patch('sd_runner.storage.preflight',return_value={'ok':True}), patch.object(Runner,'watch_deliveries',return_value=None), patch.object(Runner,'tick',tick):
        Runner(config).serve(once=True)
except RunnerRefused as error:
    print(error)
    raise SystemExit(1)
""")
        env = {**os.environ, "PYTHONPATH": os.pathsep.join([str(fixtures.ROOT), str(fixtures.ROOT.parent / "local-sd-db")])}
        first = subprocess.Popen([sys.executable, str(script), str(self.root)], env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        try:
            # Wait for the content, not for the file. `write_text` creates
            # then writes, so `exists()` is true while the marker is still
            # empty -- and this read captured `""`, which the comparison
            # below then failed against the real owner. Passed locally,
            # failed in CI, which is where the two syscalls come apart.
            deadline = time.monotonic() + 5
            owner = ""
            while not owner and first.poll() is None and time.monotonic() < deadline:
                owner = marker.read_text() if marker.exists() else ""
                if not owner:
                    time.sleep(.02)
            self.assertTrue(owner, "the first daemon never recorded its ownership")
            second = subprocess.run([sys.executable, str(script), str(self.root)], env=env, capture_output=True, text=True, timeout=5, check=False)
            self.assertEqual(second.returncode, 1, second)
            self.assertIn("runner ownership lock held", second.stdout)
            self.assertIsNone(first.poll())
            self.assertEqual(marker.read_text(), owner)
            output, error = first.communicate(timeout=7)
            self.assertEqual(first.returncode, 0, output + error)
        finally:
            if first.poll() is None:
                first.kill()
                first.communicate(timeout=5)
