#!/bin/sh
# Distribute one shared system prompt into every coding agent's global
# instructions file.
# Usage: agent-prompt.sh status|refresh|diff|capture|targets [--apply] | test [-v]
set -e

# The repo convention is DIR="$(cd "$(dirname "$0")" && pwd)", but this script
# is invoked through the ~/bin/common/agent-prompt symlink and reads
# prompt/shared.md sitting next to it, so $0 has to be walked to its real
# location first — same as repo-sync.sh and notify.sh.
SELF="$0"
while [ -L "$SELF" ]; do
  link=$(readlink "$SELF")
  case "$link" in
    /*) SELF="$link" ;;
    *)  SELF="$(dirname "$SELF")/$link" ;;
  esac
done
DIR="$(cd "$(dirname "$SELF")" && pwd)"
SRC="$DIR/prompt/shared.md"

if [ "${1:-}" = test ]; then
  shift
  exec "${PYTHON:-python3}" -m unittest discover -s "$DIR/tests" -t "$DIR" "$@"
fi

# Marker style copied from the blocks already in ~/.codex/AGENTS.md
# (codebase-memory-mcp:start). Everything outside the pair is never touched:
# these files hold hand-written per-tool content that must survive a refresh.
BEGIN="<!-- shared-prompt:start -->"
END="<!-- shared-prompt:end -->"
GENERATED="<!-- Generated by local-agent-prompt/agent-prompt.sh — edit prompt/shared.md, not this. -->"

APPLY=0
FORCE=0

# What the block looked like the last time this script wrote it, one sha256
# per target. Without it the tool can see that the installed block and
# shared.md disagree but not which of the two moved, so an ordinary source
# edit was reported as "block edited in place" and every target refused the
# write. Same env-override shape as machine-setup's state dir.
STATE_DIR="${AGENT_PROMPT_STATE:-$HOME/.config/agent-prompt}"

die() { echo "agent-prompt.sh: $*" >&2; exit 1; }

# label|path. Antigravity is deliberately absent: it reads the same
# ~/.gemini/GEMINI.md as the Gemini CLI (antigravity.google/docs/rules-workflows),
# so listing it again would write the same file twice and double-count drift.
targets() {
  cat <<EOF
claude|$HOME/.claude/CLAUDE.md
codex|$HOME/.codex/AGENTS.md
gemini|$HOME/.gemini/GEMINI.md
copilot|${COPILOT_HOME:-$HOME/.copilot}/copilot-instructions.md
opencode|$HOME/.config/opencode/AGENTS.md
EOF
}

# The block as it should appear in every target.
block() {
  managed block "$SRC"
}

# Whether a target's tool is present at all. Three ways to count, because no
# single one is sufficient:
#   - the CLI is on PATH;
#   - Antigravity is a GUI app with no CLI, and it reads the gemini target, so
#     `gemini` being absent from PATH does not make ~/.gemini/GEMINI.md moot;
#   - the config directory already exists, which covers a tool installed
#     outside PATH.
# Without this a terra machine gets config directories created for tools it
# does not have.
installed() {
  case "$1" in
    claude)   probe=claude ;;
    codex)    probe=codex ;;
    gemini)   probe=gemini ;;
    copilot)  probe=copilot ;;
    opencode) probe=opencode ;;
    *)        probe="" ;;
  esac
  if [ -n "$probe" ] && command -v "$probe" >/dev/null 2>&1; then
    return 0
  fi
  if [ "$1" = gemini ] && [ -d /Applications/Antigravity.app ]; then
    return 0
  fi
  [ -d "$(dirname "$2")" ]
}

# Prints: missing | absent | current | stale | edited | unknown
#
# The three not-current answers are the whole point. A difference alone does
# not say which side moved, and this used to guess: `status` called it STALE
# ("differs from shared.md") and `refresh` called the identical condition
# DIFFERS ("edited in place") — one of the two was always wrong. The recorded
# hash settles it. Machine still matches what we last wrote, so the source
# moved: `stale`, safe to overwrite. Machine no longer matches what we wrote,
# so someone edited the target: `edited`, refuse. No record at all — a machine
# provisioned before this existed: `unknown`, refuse, which is the old
# behaviour and self-heals after the first write.
state() { # label, path
  managed state "$2" "$1"
}

# One byte parser serves comparison, extraction, and hashing. Unmanaged bytes
# need no text encoding. Read or marker failures must not become empty hashes.
managed() { # operation, path, optional label
  python3 - "$1" "$2" "$BEGIN" "$END" "$SRC" "$GENERATED" "$STATE_DIR" "${3:-}" <<'PYEOF'
import hashlib, pathlib, sys

operation, filename, begin, end, source, notice, state_dir, label = sys.argv[1:]
begin, end = begin.encode(), end.encode()
target = pathlib.Path(filename)

def desired():
    return begin + b"\n" + notice.encode() + b"\n" + pathlib.Path(source).read_bytes() + end

def run():
    if operation == "block":
        sys.stdout.buffer.write(desired() + b"\n")
        return
    if operation == "state" and not target.exists():
        print("missing")
        return
    content = target.read_bytes()
    first, last = content.find(begin), content.find(end)
    if first < 0 and last < 0:
        if operation == "state":
            print("absent")
            return
        if operation == "extract":
            return
        raise ValueError("no managed block to hash")
    if content.count(begin) != 1 or content.count(end) != 1 or last < first:
        raise ValueError("invalid managed block markers")
    block = content[first:last + len(end)]
    if operation == "extract":
        sys.stdout.buffer.write(block)
        return
    fingerprint = hashlib.sha256(block).hexdigest()
    if operation == "hash":
        print(fingerprint)
        return
    if block == desired():
        print("current")
        return
    record = pathlib.Path(state_dir) / (label + ".sha")
    if not record.exists():
        print("unknown")
        return
    recorded = record.read_text(encoding="ascii").strip()
    print("stale" if fingerprint == recorded else "edited")

try:
    run()
except (OSError, UnicodeError, ValueError) as error:
    print(f"agent-prompt.sh: {target}: {error}", file=sys.stderr)
    sys.exit(1)
PYEOF
}

extract() { managed extract "$1"; }

hash_file() { echo "$STATE_DIR/$1.sha"; }

installed_hash() { managed hash "$1"; }

record_hash() { # label, path
  fingerprint=$(installed_hash "$2") || return 1
  mkdir -p "$STATE_DIR"
  printf '%s\n' "$fingerprint" > "$(hash_file "$1")"
}

# Replaces the block in place, or appends it when the file has no markers.
# Content outside the markers is preserved byte for byte.
write_block() {
  f="$1"
  tmp=$(mktemp)
  block > "$tmp"
  python3 - "$f" "$BEGIN" "$END" "$tmp" <<'PYEOF'
import sys, pathlib
p, b, e, blockfile = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
b, e = b.encode(), e.encode()
new = pathlib.Path(blockfile).read_bytes().rstrip(b"\n")
f = pathlib.Path(p)
f.parent.mkdir(parents=True, exist_ok=True)
old = f.read_bytes() if f.exists() else b""
i, j = old.find(b), old.find(e)
if i >= 0 and j >= 0:
    out = old[:i] + new + old[j + len(e):]
else:
    # Add separation without removing existing whitespace or converting CRLF.
    separator = b"" if not old or old.endswith(b"\n\n") else b"\n\n"
    out = old + separator + new + b"\n"
f.write_bytes(out)
PYEOF
  rm -f "$tmp"
}

# A heading that appears both inside the block and outside it means the target
# carries a stale hand-written copy of a section the block now owns — the
# refresh cannot remove it (that content is not ours), so it gets reported.
#
# Headings alone are not enough. Every agent CLI here supports an `@file`
# include, and rtk's installer uses one: it writes its own RTK.md next to the
# target and appends a bare `@RTK.md`. That line carries no heading, so a
# heading-only scan called the file clean while the agent loaded the same
# sections twice — once from the block, once through the include. It went
# unnoticed in two targets before anyone read the rendered result. So resolve
# includes one level and judge them by the headings they pull in.
dupes() {
  f="$1"
  [ -f "$f" ] || return 0
  python3 - "$f" "$BEGIN" "$END" "$SRC" <<'PYEOF'
import sys, pathlib, re
p, b, e, src = sys.argv[1:5]
target = pathlib.Path(p)
t = target.read_text(errors="surrogateescape")
i, j = t.find(b), t.find(e)
outside = (t[:i] + t[j + len(e):]) if (i >= 0 and j >= 0) else t
heads = set(re.findall(r'^#+ (.+)$', pathlib.Path(src).read_text(), re.M))

found = {}
for h in heads & set(re.findall(r'^#+ (.+)$', outside, re.M)):
    found[h] = None

# One level only: an include that itself includes is rare here, and following
# arbitrary depth would need cycle handling for no real gain.
for inc in re.findall(r'^@(\S+)\s*$', outside, re.M):
    q = pathlib.Path(inc).expanduser()
    if not q.is_absolute():
        q = target.parent / q
    try:
        it = q.read_text(errors="surrogateescape")
    except OSError:
        continue
    for h in heads & set(re.findall(r'^#+ (.+)$', it, re.M)):
        found.setdefault(h, inc)

for h in sorted(found):
    via = found[h]
    print(f"{h} (via @{via})" if via else h)
PYEOF
}

cmd_status() {
  [ -f "$SRC" ] || die "no prompt/shared.md to distribute"
  echo "source  : $SRC ($(wc -l < "$SRC" | tr -d ' ') lines)"
  echo
  targets | while IFS='|' read -r label path; do
    if ! installed "$label" "$path"; then
      echo "  SKIP    $label — not installed on this machine"
      continue
    fi
    st=$(state "$label" "$path")
    case "$st" in
      current) echo "  ok      $label $path" ;;
      stale)   echo "  STALE   $label $path — shared.md moved; 'refresh --apply' writes it" ;;
      edited)  echo "  DIFFERS $label $path — block edited in place since it was written" ;;
      unknown) echo "  UNKNOWN $label $path — differs, and no record of what was last written" ;;
      absent)  echo "  ABSENT  $label $path — file exists, no managed block yet" ;;
      missing) echo "  MISSING $label $path — file does not exist yet" ;;
    esac
    dupes "$path" | while read -r h; do
      echo "          duplicate section outside the block: \"$h\" — remove it by hand"
    done
  done
  return 0
}

# Returns failure only for a conflict that requires explicit overwrite approval.
refresh_conflict() { # state, label, path
  if { [ "$1" = edited ] || [ "$1" = unknown ]; } && [ "$FORCE" -eq 0 ]; then
    if [ "$1" = edited ]; then
      echo "  DIFFERS $2 $3 — block edited in place; keep it with"
    else
      echo "  UNKNOWN $2 $3 — differs, and nothing recorded what was last"
      echo "          written here, so which side moved cannot be told. Check"
      echo "          'diff', then keep it with"
    fi
    echo "          'capture $2 --apply', or discard it with 'refresh --force'"
    return 1
  fi
}

cmd_refresh() {
  [ -f "$SRC" ] || die "no prompt/shared.md to distribute"
  [ "$APPLY" -eq 1 ] || echo "mode    : DRY RUN — nothing will be written; re-run with --apply"
  # Inspect every target before recording even unchanged hashes. This prevents
  # known conflicts from leaving an order-dependent, partly refreshed fleet.
  targets | (
    failed=0
    while IFS='|' read -r label path; do
      installed "$label" "$path" || continue
      if st=$(state "$label" "$path"); then
        refresh_conflict "$st" "$label" "$path" || failed=1
      else
        failed=1
      fi
    done
    [ "$failed" -eq 0 ]
  ) || return 1
  targets | while IFS='|' read -r label path; do
    if ! installed "$label" "$path"; then
      echo "  SKIP    $label — not installed on this machine"
      continue
    fi
    # Recheck after preflight; another process can change a target meanwhile.
    st=$(state "$label" "$path") || return 1
    refresh_conflict "$st" "$label" "$path" || return 1
    if [ "$st" = current ]; then
      # Record even though nothing was written. A machine that was already in
      # sync never takes the write path, so without this it would hold no hash
      # at all and the first ordinary edit to shared.md would come back as
      # `unknown` on every target — the very guess this is meant to replace.
      [ "$APPLY" -eq 1 ] && record_hash "$label" "$path"
      echo "  ok      $label unchanged"
      continue
    fi
    if [ "$APPLY" -eq 1 ]; then
      write_block "$path"
      record_hash "$label" "$path"
      echo "  wrote   $label $path ($st)"
    else
      echo "  [dry-run] would write $label $path ($st)"
    fi
  done
  return 0
}

cmd_diff() {
  targets | while IFS='|' read -r label path; do
    echo "== $label $path"
    if [ ! -f "$path" ]; then
      echo "  (file does not exist)"
      continue
    fi
    have=$(mktemp); want=$(mktemp)
    if ! extract "$path" > "$have" || ! block > "$want"; then
      rm -f "$have" "$want"
      return 1
    fi
    printf '\n' >> "$have"
    if diff -u "$have" "$want" > /dev/null; then
      echo "  (identical)"
    else
      diff -u "$have" "$want" | sed -n '3,$p' | sed 's/^/  /'
    fi
    rm -f "$have" "$want"
  done
  return 0
}

# Pull a target's block back into the repo, for when the prompt was edited in
# place (Claude Code's /memory writes ~/.claude/CLAUDE.md directly). Refuses a
# target with no markers rather than guessing which part of it is shared.
cmd_capture() {
  label="${1:-claude}"
  path=$(targets | grep "^$label|" | cut -d'|' -f2)
  [ -n "$path" ] || die "unknown target '$label' (see: agent-prompt.sh targets)"
  [ -f "$path" ] || die "$path does not exist"
  grep -qF "$BEGIN" "$path" || die "$path has no managed block — nothing to capture"
  cap=$(mktemp)
  have=$(mktemp)
  if ! extract "$path" > "$have"; then
    rm -f "$cap" "$have"
    return 1
  fi
  sed -e "1d" -e "\$d" "$have" | sed '1{/^<!-- Generated by/d;}' > "$cap"
  rm -f "$have"
  if cmp -s "$cap" "$SRC"; then
    echo "  ok      shared.md already matches $label"
    rm -f "$cap"
    return 0
  fi
  if [ "$APPLY" -eq 1 ]; then
    mv "$cap" "$SRC"
    # shared.md now equals this target's block, so record it: without this the
    # target that was just captured from would read `unknown` on the next
    # refresh and demand a --force to accept its own content back.
    record_hash "$label" "$path"
    echo "  captured $label -> prompt/shared.md"
  else
    echo "  [dry-run] would capture $label -> prompt/shared.md"
    diff -u "$SRC" "$cap" | sed -n '3,$p' | sed 's/^/  /' || :
    rm -f "$cap"
  fi
  return 0
}

VERB=""
ARG=""
for a in "$@"; do
  case "$a" in
    --apply) APPLY=1 ;;
    --force) FORCE=1 ;;
    -h|--help|help)
      cat <<'HELPEOF'
usage: agent-prompt.sh status|refresh [--apply] [--force]|diff|capture [target] [--apply]|targets|test [-v]

One shared system prompt, distributed into every coding agent's global
instructions file. The source of truth is prompt/shared.md in this folder.

  status     per-target report: is the managed block present and current
  refresh    write the block into every target (dry run without --apply)
  diff       unified diff of each target's block against shared.md
  capture    pull a target's block back into prompt/shared.md, for when the
             prompt was edited in place (default target: claude)
  targets    list the resolved file paths
  test       run isolated prompt-distribution tests; extra arguments go to unittest

  --apply    actually write. WITHOUT IT REFRESH AND CAPTURE ARE DRY RUNS.
  --force    (refresh) overwrite a block that was edited in place. Without it
             refresh reports all known conflicts and exits 1 before writing,
             so an edit made
             through Claude Code's /memory is never silently discarded.

A target that differs from shared.md is one of three things, and which one is
decided by the sha256 of the block as it was last written, kept in
$AGENT_PROMPT_STATE (default ~/.config/agent-prompt):

  STALE    the target still matches what was written; shared.md moved.
           `refresh --apply` writes it, no --force needed.
  DIFFERS  the target no longer matches what was written: someone edited the
           block in place. Refused; keep it with `capture`, or `--force`.
  UNKNOWN  it differs and nothing is recorded — a machine provisioned before
           the hash existed. Refused; the first `refresh --apply` records one
           for every target, including the ones already current.

The block is delimited by <!-- shared-prompt:start --> / <!-- shared-prompt:end -->.
Content outside those markers is preserved byte for byte — every one of
these files also holds hand-written per-tool content, and ~/.codex/AGENTS.md
holds considerably more of it than the shared block does.

Antigravity has no entry of its own: it reads the same ~/.gemini/GEMINI.md as
the Gemini CLI, so the gemini target covers both.
HELPEOF
      exit 0
      ;;
    status|refresh|diff|capture|targets)
      if [ -z "$VERB" ]; then VERB="$a"; else ARG="$a"; fi ;;
    *)
      [ -n "$VERB" ] && [ -z "$ARG" ] && ARG="$a" ;;
  esac
done

case "$VERB" in
  status)  cmd_status ;;
  refresh) cmd_refresh ;;
  diff)    cmd_diff ;;
  capture) cmd_capture "$ARG" ;;
  targets) targets | sed 's/|/  /' ;;
  *)
    echo "usage: $(basename "$0") status|refresh [--apply] [--force]|diff|capture [target]|targets|test [-v]" >&2
    exit 1
    ;;
esac
